import AdminHeader from "@/components/admin/AdminHeader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trendy-Treasures/dashboard",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main className="flex">
        <AdminHeader />
        <div className="flex-1 p-8">
        {children}
        </div>
    </main>
  );
}
